{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 1}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_goals_get", "rerun": "0"}, "1": {"status": "ERROR", "message": "@pytest.fixture\n    def create_gols_data():\n        random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=10))\n>       with open('Test_data/create_goals.json', 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'Test_data/create_goals.json'\n\nTests/test_goals_methods.py:32: FileNotFoundError\n", "test_name": "test_goals_send_data", "rerun": "0"}, "2": {"status": "FAIL", "message": "   TypeError: 'dict' object is not callable\n", "test_name": "test_goals_update_data", "rerun": "0"}}, "suite_name": "Tests/test_goals_methods.py"}}}, "date": "July 14, 2024", "start_time": 1720971250.621454, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "1", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}